version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: clientes_db
    depends_on:
      - mysql
    command: >
      sh -c "
      while ! echo exit | telnet mysql 3306 2>/dev/null | grep -q 'Connected'; do
        echo 'Waiting for MySQL to be ready...';
        sleep 3;
      done;
      npm start"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientes_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      args:
        VITE_ENDPOINT_API: http://localhost:3000
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - VITE_ENDPOINT_API=http://localhost:3000
    depends_on:
      - backend

volumes:
  mysql-data:
